### ISSUE TITLE
how add custom inline button row 2 

### ISSUE THREAD

**Issue by tbz-ayhan** [manzoorwanijk/wptelegram#2]
How Add Custom Inline Button Row Two 

public function get_inline_keyboard( $method_params ) {

		$inline_url_button = $this->options->get( 'inline_url_button' );
		$inline_button_text = $this->options->get( 'inline_button_text' );

		if ( 'on' !== $inline_url_button ) {
			return false;
		}
		
		// row 1
		$default_button = array(
			'text'	=> '🔗 ' . $inline_button_text,
			'url'	=> self::$post_data->get_field( 'full_url' ),
		);
		// row 2
		**$default_button2 = array(
			'text'	=> '🔗 Support',
			'url'	=> 'https://telegram.me/TbzAyhan',
		);**

		$default_button = (array) apply_filters( 'wptelegram_p2tg_default_inline_button', $default_button, self::$post, $method_params );

		$inline_keyboard[][] = $default_button;

		return (array) apply_filters( 'wptelegram_p2tg_inline_keyboard', $inline_keyboard, self::$post, $method_params );
	}

![Uploading image.png…]()

**Comment by manzoorwanijk** [comment]
You can make use of `wptelegram_p2tg_inline_keyboard` filter like this:

```PHP
add_filter( 'wptelegram_p2tg_inline_keyboard', function ( $inline_keyboard, $post ) {

	// create the row
	$second_row = [
		[
			'text'	=> 'First Button',
			'url'	=> 'https://something.com',
		],
		[
			'text'	=> 'Second Button',
			'url'	=> 'https://somethingelse.com',
		],
	];

	// push the row into the keyboard
	$inline_keyboard[] = $second_row;

	return $inline_keyboard;
}, 10, 2 );
```
